- name: register example
  hosts: local
  gather_facts: no

  tasks:
   - name: get hostname
     command: hostname
     register: host_output

   - name: print hostname
     debug:
       msg: "this is srujan {{ host_output.stdout }}"